language: python
sudo: false
python:
  - "2.7"
env:
  - TZ=Europe/Kiev
cache:
  directories:
    - eggs
services:
  - couchdb
before_install:
  - pip install setuptools==7.0
  - python2 bootstrap.py
install:
  - bin/buildout -N
before_script:
  - curl -X PUT localhost:5984/audit_tests
script:
  - bin/nosetests
after_success:
  - bin/coveralls

