language: python
sudo: false
python:
  - "2.7"
env:
  - TZ=Europe/Kiev
cache:
  directories:
    - eggs
before_install:
  services:
    - couchdb
  - pip install setuptools==7.0
  - python2 bootstrap.py
before_script:
  - curl -X PUT localhost:5984/audit_tests
install:
  - bin/buildout -N
script:
  - bin/nosetests
after_success:
  - bin/coveralls

